oc scale deploy ibm-cp4a-operator --replicas=1
oc scale deploy ibm-zen-operator --replicas=1
oc scale deploy ibm-iam-operator --replicas=1
oc scale deploy ibm-commonui-operator --replicas=1
oc scale deploy ibm-common-service-operator --replicas=1
oc scale deploy ibm-odm-operator --replicas=1
oc scale deploy zen-core --replicas=1
oc scale deploy zen-core-api --replicas=1
oc scale deploy ibm-content-operator --replicas=1
oc scale deploy ibm-dpe-operator --replicas=1
oc scale deploy ibm-cp4a-wfps-operator --replicas=1
oc scale deploy ibm-insights-engine-operator --replicas=1
oc scale deploy flink-kubernetes-operator --replicas1
oc scale deploy iaf-system-entity-operator --replicas=1
oc scale deploy ibm-ads-operator --replicas=1
oc scale deploy ibm-pfs-operator --replicas=1
oc scale deploy ibm-workflow-operator --replicas=1
oc scale deploy icp4a-foundation-operator --replicas=1
oc scale deploy operand-deployment-lifecycle-manager --replicas=1
oc scale deploy postgresql-operator-controller-manager-1-22-7 --replicas=1
oc scale deploy ibm-events-operator-v5.0.1 --replicas=1
oc annotate cluster zen-metastore-edb --overwrite k8s.enterprisedb.io/hibernation=off 
oc annotate cluster common-service-db --overwrite k8s.enterprisedb.io/hibernation=off
oc annotate cluster ibm-bts-cnpg-ibm-cp4ba-dev-cp4ba-bts --overwrite k8s.enterprisedb.io/hibernation=off
oc scale deploy ibm-bts-operator-controller-manager --replicas=1
oc patch bts cp4ba-bts --type merge --patch '{"spec":{"replicas":1}}'
oc scale deploy ibm-nginx --replicas=2
oc scale deploy ibm-nginx-tester --replicas=1
oc scale sts zen-minio --replicas=3
oc scale deploy usermgmt --replicas=1
oc scale deploy zen-core --replicas=1
oc scale deploy zen-core-api --replicas=1
oc scale deploy zen-watcher --replicas=1
oc scale deployment zen-audit --replicas=1
oc scale deploy common-web-ui --replicas=1
oc scale deploy mycluster-insights-engine-flink --replicas=2
oc scale deploy mycluster-insights-engine-flink-taskmanager --replicas=1
oc scale deploy mycluster-insights-engine-management --replicas=1
oc scale deploy mycluster-insights-engine-cockpit --replicas=1
oc scale deploy mycluster-pbk-ae-deployment --replicas=1
oc scale deploy mycluster-workspace-aae-ae-deployment --replicas=1
