###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: processmining-subscription
  namespace: cp4baProjectName
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-automation-processmining
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace

