###############################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2021. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
apiVersion: core.automation.ibm.com/v1beta1
kind: Cartridge
metadata:
  namespace: cp4baProjectName
  name: icp4ba
spec:
  description: cartridge for all CP4BA
  license:
    accept: true
  version: 1.0.0
